Adding Async Methods to server
veliovgroup/Meteor-Files pull request #884
Opened 2023-12-21 20:18 UTC by bratelefant

This is a first try on async methods as a PR draft. Updated eslint and mocha testing as well; `core.js` and `cursor.js` were a starting point. Work is progressing on `server.js`.

Related to #865

2023-12-27 22:26 UTC, bratelefant commented
Hi guys, please comment on this first attempt. In order to better understand what's going on I decided to add some tests for the server part, FilesCollection, core and cursor. Unfortunately this adds overall dependencies, especially in `package.js`; if anyone knows how to limit these dependencies to dev / testing, pleas let me know. Also tweaked the `.eslintrc` a little bit. Core and cursor now additionally have async methods. Work on `server.js` is in progress.

I suggest that the async versions of all the methods do not use any callbacks but throw errors instead and return promises resolving the results, cf. `FilesCollection.addFileAsync` for example.

Which callbacks need async versions? E.g. for my project, I need an async version of `protected()`, since I do policy checks against the db here, which will be async as well of course. I guess an async version `onAfterUpload` could be helpful, since the aws sdk v3 for example also uses async functions to send putObject requests etc.

2024-01-04 19:53 UTC, harryadel commented
@bratelefant Thank you for your efforts, brother. What's the status of this PR?

2024-01-05 13:45 UTC, bratelefant commented
Gave it a pause to get some feedback first and pursued other tasks. Getting back to this soon.

2024-01-05 16:13 UTC, harryadel requested changes
I'm glad this wasn't a hit-and-run type of PR. You took the time added tests and improved the overall stability of this package. What remains is updating the docs and adding a CI to run the packages.

2024-01-05 16:13 UTC, harryadel commented on tests/core.test.js
> +/* global describe, beforeEach, it */
Amazing work adding new tests :+1:

2024-01-05 16:13 UTC, harryadel commented on package.js
> +  'supports-color': '6.1.0',
Packages like `supports-color`, `diff` and `fake-timers` aren't used in the code. Are you going to use them later on?

2024-01-05 18:10 UTC, bratelefant commented on tests/core.test.js
> +/* global describe, beforeEach, it */
Thanks, thought this could help ensuring the async functions behave well...

2024-01-05 18:12 UTC, bratelefant commented on core.js
> +      type: String,
I'll try to take care of this; accidentially use prettier in vsc and then lint fix again, this is where stuff like this happens...

2024-01-05 18:16 UTC, bratelefant commented on package.js
> +  'supports-color': '6.1.0',
Added this because I got several errors at some point while testing, from peer deps from chai or so

2024-01-05 18:25 UTC, harryadel commented
@bratelefant I'm going to clone it if you're not going to release. But it's ok to release unfinished work in incremental bits so it can be tested out like we did with [beta releases](https://github.com/Meteor-Community-Packages/meteor-collection2/pull/444) for collection2.

2024-01-05 18:27 UTC, bratelefant commented on core.js
> +  async updateAsync() {
I just went analogue to the sync update version. Maybe since this is supposed to just forward the method to the collections method ("link Mongo.Collection update method") one would not expect to have this method altered too much

2024-01-05 18:33 UTC, bratelefant commented
> @bratelefant I'm going to clone it if you're not going to release. But it's ok to release unfinished work in incremental bits so it can be tested out like we did with [beta releases](https://github.com/Meteor-Community-Packages/meteor-collection2/pull/444) for collection2.

Ok, I might get a beta up. Should the package name still be "ostrio:files"? What version number do you suggest, like 3.0.0-alpha.1?

2024-01-05 18:35 UTC, harryadel commented
@bratelefant Only @dr-dimitru has the right to publish the package. It might be nuisance since you'd have to change the package name and publish it yourself then revert changes before merging this PR . So, I take it back I'll clone things locally and give it a go.

2024-01-05 18:40 UTC, dr-dimitru commented
@harryadel @bratelefant feel free to let me know what's exactly needed for the beta-release

2024-01-05 18:47 UTC, harryadel commented
@dr-dimitru oh you're listening in? :grin: Just append change the version to `2.4-beta.1` and publish it as you normally do

2024-01-05 19:58 UTC, dr-dimitru requested changes
@bratelefant please start with reverting non-functional changes. Otherwise it would be easy to miss an error during review. Please remain codebase that doesn't require functional changes unchanged

2024-01-05 19:58 UTC, dr-dimitru commented on core.js
> +      data._storagePath || this.storagePath(Object.assign({}, data, ds));
?

2024-01-05 19:58 UTC, dr-dimitru commented on core.js
> +    );
?

2024-01-05 19:58 UTC, dr-dimitru commented on core.js
> +    );
?

2024-01-05 19:59 UTC, dr-dimitru commented
@harryadel thank you for the suggestion, — will do

2024-01-05 20:01 UTC, dr-dimitru commented
@bratelefant please see my review, I assume you've satisfied your linter and now my is freaking out. Also please advise why we need `package.json` as a new file here?

2024-01-05 20:14 UTC, dr-dimitru commented
@bratelefant thank you for the work done so far, like the test-suite — it looks great!
Beta release is out — https://packosphere.com/ostrio/files/3.0.0-beta.1 🥳

2024-01-05 20:49 UTC, harryadel commented
That's the type of cooperation I wanna see from the community. Great job guys @dr-dimitru @bratelefant

2024-01-06 10:23 UTC, bratelefant commented on cursor.js
> +    return this.cursor.fetch()[++this._current];
I consider this a bug fix, is that correct?

2024-01-06 13:12 UTC, bratelefant commented on server.js
> +  async writeAsync(buffer, _opts = {}, _proceedAfterUpload) {
This behaves now a bit differently, instead of returning `this` it will resolve to the fileRef

2024-01-06 20:20 UTC, dr-dimitru requested changes
@bratelefant please see my review and questions

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +      throw (new Meteor.Error(404, 'No such file'));
@bratelefant Seems like two `()` aren't necessary here

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +    );
@bratelefant seems like non-functional change, let's revert it please

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +  }
@bratelefant @harryadel a question — would it make sense if we write this and similar methods this way? Do you see any pros/cons?

```js
  getAsync() {
    this._collection._debug('[FilesCollection] [FilesCursor] [getAsync()]');
    return this.cursor.fetchAsync();
  }
```

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +    return this.cursor.fetch()[++this._current];
Great catch! Kudos 🙏

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +    return (await this.cursor.fetchAsync())[++this._current];
@bratelefant seems like first parenthesis `()` isn't necessary here

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
> +    );
@bratelefant Let's use same style here as well. Just want to make sure old code and new changes look, feel, and read in the same way

2024-01-06 20:20 UTC, dr-dimitru commented on cursor.js
>      this.cursor.fetch()[--this._current];
@bratelefant similar to `next()` we got to return value here

2024-01-06 20:20 UTC, dr-dimitru commented on server.js
> +  async _prepareUploadAsync(opts = {}, userId, transport) {
@bratelefant what pros or reason converting "private" lib methods to async/await?

2024-01-06 20:20 UTC, dr-dimitru commented on server.js
> +    );
Can we use the same style here as well? Just want to make sure old code and new changes look, feel, and read in the same way

2024-01-06 20:20 UTC, dr-dimitru commented on server.js
> +  async writeAsync(buffer, _opts = {}, _proceedAfterUpload) {
@bratelefant I'd move `_proceedAfterUpload` to 3rd argument and wrap `write` with Meteor's `wrapAsync`, two reasons:
1. Won't behave differently
2. this would follow DRY principle and minimize surface for errors/bugs

lmk wdyt

2024-01-06 20:22 UTC, dr-dimitru commented
> @bratelefant please see my review, ~I assume you've satisfied your linter and now my is freaking out~ (solved with NPM update). Also please advise why we need `package.json` as a new file here?

lmk if we can avoid having `package.json` and move its scripts into "Testing" section of the docs

2024-01-06 20:26 UTC, bratelefant commented
> @bratelefant please see my review and questions

Will do that tomorrow ;)

2024-01-06 20:28 UTC, bratelefant commented
> > @bratelefant please see my review, ~I assume you've satisfied your linter and now my is freaking out~ (solved with NPM update). Also please advise why we need `package.json` as a new file here?
> 
> lmk if we can avoid having `package.json` and move its scripts into "Testing" section of the docs

Wanted to use it primarily for github actions, did commit them a min ago. But of course we could get rid of that and move everything into the actions. package.json seems more standard to me though and is convenient for local testing

2024-01-09 21:34 UTC, dr-dimitru commented
@bratelefant 

1. lmk once it's ready for another beta so community can run tests
2. still looking forward to discuss [this](https://github.com/veliovgroup/Meteor-Files/pull/884#discussion_r1443849438), [that](https://github.com/veliovgroup/Meteor-Files/pull/884#discussion_r1443848527), [and this](https://github.com/veliovgroup/Meteor-Files/pull/884#discussion_r1443847074) questions;

2024-01-09 21:36 UTC, dr-dimitru commented on cursor.js
> +  }
@bratelefant I see this one was updated but it still starts with `async getAsync()` while I believe `async` keyword isn't necessary since `.fetchAsync()` would return a promise

2024-01-10 08:30 UTC, bratelefant commented
@dr-dimitru can we add @jankapunkt as a reviewer here?

2024-01-10 09:05 UTC, dr-dimitru commented
@bratelefant I've added @jankapunkt as reviewer

2024-01-10 10:49 UTC, harryadel commented
Should `onBeforeRemove` be made async?

2024-01-10 11:21 UTC, dr-dimitru commented
> Should `onBeforeRemove` be made async?

@harryadel @bratelefant @jankapunkt I don't think it's viable to create `*Async` version of each "hook", shall we simply make all existing hooks with async in mind?

2024-01-10 11:43 UTC, harryadel commented
>shall we simply make all existing hooks with async in mind?
Seems like solid option IMO. 

What made me raise this question is that I was going through my application and starting to convert `onBeforeUpload` to `onBeforeUploadAsync` and so on but then I found not all hooks are async-ified. I think given the spirits of 3.0 of Meteor and the changes being worked on in this PR are made under major bump then it's to have all hooks be made with async in mind. What do you think? @bratelefant @jankapunkt @storytellercz

2024-01-10 12:24 UTC, bratelefant commented
I definitely would provide async versions for all hooks. Is there a standard way on how meteor core deals with this that we could adopt? My approach would be to add an `...Async` version of the hook which will be called if async methods get invoked. Cf. `protectedAsync` for example. You'd want to be able to wait for db queries checking policies or things like that, guess the same applies to `interceptDownload` or `onBeforeUpload`, which I use for S3 stuff, so I wanted to add `interceptDownloadAsync` and `onBeforeUploadAsync` as well.

2024-01-10 12:31 UTC, bratelefant commented
> > Should `onBeforeRemove` be made async?
> 
> @harryadel @bratelefant @jankapunkt I don't think it's viable to create `*Async` version of each "hook", shall we simply make all existing hooks with async in mind?

You mean if we transition our app that uses Meteor-Files it's up to the dev to change the hook to an async one, and the async versions calling the hooks await hook to be finished?

2024-01-10 16:29 UTC, bratelefant commented
> > > > Should `onBeforeRemove` be made async?
> > > 
> > > 
> > > @harryadel @bratelefant @jankapunkt I don't think it's viable to create `*Async` version of each "hook", shall we simply make all existing hooks with async in mind?
> > 
> > 
> > You mean if we transition our app that uses Meteor-Files it's up to the dev to change the hook to an async one, and the async versions calling the hooks await hook to be finished?
> 
> @bratelefant I assume we only need to check if returned result from "hook" is _Promise_ or not. If it isn't a _Promise_ — it will act as it is now. If it has returned a _Promise_ — wait for resolve. wdyt?

Sounds like a good approach, reducing redundant code a bit. I'll give it a shot in this PR.

What's considered the most bulletproof way of checking for a function returning a promise?

2024-01-10 19:00 UTC, dr-dimitru commented on server.js
> +  async _prepareUploadAsync(opts = {}, userId, transport) {
@bratelefant let's discuss this one. I assume similar to hooks — for "private" methods we should simply rewrite existing codebase to async/await without creating `*Async` versions. wdyt?

2024-01-10 19:01 UTC, dr-dimitru commented
@bratelefant yes, I think in the same way at first old code won't require any changes, new "await" code will simply work once `async` keyword added in front on hook registration

> What's considered the most bulletproof way of checking for a function returning a promise?

Found this in FlowRouter's codebase (perhaps you can also check that `.catch` is a function in a right-hand of condition):
```js
Object.prototype.toString.call(d) === '[object Promise]' || d.then && Object.prototype.toString.call(d.then) === '[object Function]'
```

> Edit: I removed the onBeforeUpdateAsync. The hook gets called in both _prepareUpload and _prepareUploadAsync'. In the latter I just await` the returned value which is ok if a plain Boolean is returned as well.

Please see [this conversation](https://github.com/veliovgroup/Meteor-Files/pull/884#discussion_r1443848527)

2024-01-12 17:38 UTC, bratelefant commented
ok, made all internal methods async and hooks async. For the middleware I switch to calling async db methods, if available (I simply check if `collection.findOneAsync` is a func, hope this will do). Guess we need some tests for the middleware. However, I successfully did a download (incl. interceptRequest and onAfterUpload hooks for s3, and async protected check) without any errors from `WARN_WHEN_USING_OLD_API` :)

2024-01-12 18:43 UTC, bratelefant commented
`_finishUpload` is now async but will not use legacy fiber methods. So if we leave it this way this would be a breaking change for Meteor version <2.8. This is a general question whether to throw out all fiber methods or keep them.

2024-01-15 06:24 UTC, harryadel commented
>_finishUpload is now async but will not use legacy fiber methods. So if we leave it this way this would be a breaking change for Meteor version <2.8. This is a general question whether to throw out all fiber methods or keep them.
 
 I'm leaning more towards throwing out all fibers methods. Meteor itself is undergoing a major version upgrade and breaking changes so why not the packages? If someone still wants to use fibers they won't be using 3.0 in the first place. Maybe the Jan twins can shed some light on this @StorytellerCZ @jankapunkt 

@dr-dimitru Can we release a new beta so we can test things out?

2024-01-15 11:51 UTC, dr-dimitru commented
@harryadel I agree and believe that major release can have breaking API changes, isolating Meteor's env using `.versionsFrom`

@bratelefant let's have clean new async/await compatible and Fiber-less API with new release. Older version are fully compatible with `meteor@pre-3.0.0`

2024-01-15 11:57 UTC, dr-dimitru commented
@bratelefant @harryadel @jankapunkt `3.0.0-beta.2` [is out](https://packosphere.com/ostrio/files/3.0.0-beta.2)!

2024-01-16 06:29 UTC, bratelefant commented
Ok, so for the cursors and collections I'll throw out all `.fetch()` and `.count()` methods etc, only `.fetchAsync()` and `.countAsync()` will remain, as they align with meteors method names. What about additional methods like `.next()` and `.previous()` resp. `.nextAsync()` and `.previousAsync()`? Should we name them with the `Async` suffix or without?

2024-01-16 07:01 UTC, dr-dimitru commented
@bratelefant I thought we want to keep methods naming untouched, just change its underlying logic making then Fiber-less and async/await-driven

@harryadel @jankapunkt wdyt on methods naming? is it necessary to rename methods (_taking in account Meteor's team planning to rename them back one day_)?

2024-01-16 07:23 UTC, bratelefant commented
I personally would prefer to align with meteor 3.0 naming for the forwarded methods (like `.fetchAsync` etc.) and stick with the naming of Meteor-Files-specific functions (like `.next()` etc.) This way there's no confusion about a `.fetch()` which needs to be `await`ed and we minimize the possible number of changes to make once the `Async` suffix gets removed in meteor core some day. (Is this planned?)

2024-01-16 07:39 UTC, harryadel commented
>There are only two hard things in Computer Science: cache invalidation and naming things.

:smile: 

@bratelefant 
> (Is this planned?)

Yes but not anytime soon

It's very important here that we're talking about the same thing guys.

>Ok, so for the cursors and collections I'll throw out all .fetch() and .count() methods etc, only .fetchAsync() and .countAsync() will remain, as they align with meteors method names. What about additional methods like .next() and .previous() resp. .nextAsync() and .previousAsync()? Should we name them with the Async suffix or without?

>@bratelefant I thought we want to keep methods naming untouched, just change its underlying logic making then Fiber-less and async/await-driven

>@harryadel @jankapunkt wdyt on methods naming? is it necessary to rename methods (taking in account Meteor's team planning to rename them back one day)?

I agree with @dr-dimitru comment, don't change any property/method name that doesn't need to be changed. Only make it async-compliant by changing underlying code as little as needed. Don't go overboard with it. This serves two purposes first it makes the migration easier as there're less name changes, second lessens the effort on your behalf.   

To put it in more concrete examples so we're all on the same page:

`interceptDownload` becomes `interceptDownload` as is, the only difference is that you can prepend `async` and write asynchronous code within it. You don't change it to `interceptDownloadAsync`.

2024-01-16 07:53 UTC, dr-dimitru commented
@bratelefant I'd like to point out that my recommendations are focused primary on simplifying codebase and reducing your workload now, and consequently its further maintenance

> `interceptDownload` becomes `interceptDownload` as is, the only difference is that you can prepend `async` and write asynchronous code within it. You don't change it to `interceptDownloadAsync`. 

@harryadel yes, and yes, and removing the last `proceedAfterUpload` argument from methods like `load`, `write`, and `addFile`. Is is feasible to simply wrap these and similar methods into `Meteor.wrapAsync` top provide await/async versions of methods?

2024-01-16 12:24 UTC, bratelefant commented
> > There are only two hard things in Computer Science: cache invalidation and naming things.
At least for the frontend guys don't forget centering a div ;)

> It's very important here that we're talking about the same thing guys.

> I agree with @dr-dimitru comment, don't change any property/method name that doesn't need to be changed. Only make it async-compliant by changing underlying code as little as needed. Don't go overboard with it. This serves two purposes first it makes the migration easier as there're less name changes, second lessens the effort on your behalf. You've been doing tremendous work here and we respect your time. 😉

That's fine with me, sounds reasonable. Eg. I'll make `addFile` async and throw out `addFileAsync`.

> To put it in more concrete examples so we're all on the same page:
> 
> `interceptDownload` becomes `interceptDownload` as is, the only difference is that you can prepend `async` and write asynchronous code within it. You don't change it to `interceptDownloadAsync`.

I considered this a hook and already removed the need for `Async` versions, also for some other hooks (like `onAfterUpload` and `onAfterRemove` for example)

2024-01-16 12:28 UTC, harryadel commented
@bratelefant 
>At least for the frontend guys don't forget centering a div ;)

I thought that's a backend problem :sweat_smile: 

Thank you for your efforts brother :pray:

2024-01-16 13:43 UTC, bratelefant commented
Alright, did throw out all fiber methods in `core.js` and `cursor.js`, i.e. `remove`, `update`, `fetch`... are out, `removeAsync, `fetchAsync`, `updateAsync`... remain, to match meteors async methods.

The "new" methods from files like `get` and `next`, `previous` are now async only, and there's no more `getAsync`, `nextAsync`, `previousAsync` etc.

If this is the way to go I'd also update `server.js`. Tests fail here since they still assume that fiber methods exist.

Anyways, guess we need some proper testing of the middleware, especially to check how this works with express.

2024-01-17 16:56 UTC, harryadel commented
@bratelefant I'm keeping a close eye on your work and currently migrating our application. Please do let @dr-dimitru when you're done so he can release a new PR. Thanks!

2024-01-17 17:00 UTC, bratelefant commented
> @bratelefant I'm keeping a close eye on your work and currently migrating our application. Please do let @dr-dimitru when you're done so he can release a new PR. Thanks!

Ok, will do that soon. I'm currently migrating all changes in my last two commits to my own app for end-to-end testing. However, I'm still stuck on meteor 2.14 due to the [minisat issue](https://github.com/meteor/meteor/issues/12902).

Also, I'll try to add some testing to the middleware.

2024-01-17 19:40 UTC, bratelefant commented
Ok @dr-dimitru and @harryadel , 

did some testing with my app and some modifications related with method renaming. Integration and end-to-end tests seem fine on meteor 2.14 at least for what I use (mainly up & download, s3 integration with interceptRequest, onAfterUpload, protected). 

A few things to consider for migrating an app to use this:

- all "standard" fiber methods (`fetch`, `remove`...) got thrown out and need to be replaced by their async equivalents (`fetchAsync`, `removeAsync`...)
- all Meteor-Files-specific methods (`addFile`, `next`, `prev`, `load`, ...) keep their names but now return a promise.
- all hook calls from inside Meteor-Files should be "awaited", i.e. it should be fine if they return a promise now.
- if you need a current user in a hook, e.g. like `this.user()` in the context of `protected`, this is now also replaced by the async `this.userAsync()`.
- callbacks a la `(err,res) => ...` now got removed from async methods, use `try { ... } catch (e) { ... }` instead to call the new async methods.

Of course there could still be bugs around, please report or comment on this.

Ready for another beta from my part.

2024-01-19 20:14 UTC, dallman2 commented
> @bratelefant @harryadel @jankapunkt `3.0.0-beta.2` [is out](https://packosphere.com/ostrio/files/3.0.0-beta.2)!

I may be missing something here, but when I try to specify this version (`ostrio:files@3.0.0-beta.2`) in my meteor packages files, it does not work with Meteor 3. Where is the repository/ branch that contains the beta 2 source code?

2024-01-20 06:02 UTC, bratelefant commented
Hi

> > @bratelefant @harryadel @jankapunkt `3.0.0-beta.2` [is out](https://packosphere.com/ostrio/files/3.0.0-beta.2)!
> 
> I may be missing something here, but when I try to specify this version (`ostrio:files@3.0.0-beta.2`) in my meteor packages file, it does not work with Meteor 3. Where is the repository/ branch that contains the beta 2 source code?
> 
> EDIT: I cloned the repository that originated this PR. With a few modifications, I was able to get it working with meteor 3. Namely:
> 
> * Commenting out the `api.versionsFrom('2.14');` call in `package.js`
Interesting, thought this would still enable the package for version 3.0-beta; 

> * Wrapping lines 368 - 384 (ie all of the `check` calls) in a `try` / `catch` to prevent the app from crashing
Question here is: Was any of the check faulty, in the sense that: Was your configuration for Meteor-Files in the constructor correctly provided according to the docs but an error was thrown anyway? Otherwise I'd consider this normal behavior, since starting from node v15 unhandled promise rejections terminate the app, so you'd have to take care of managing this in your app.
 
> Is the goal of this PR to support Meteor 3? Or to bring the package up to date with Meteor 2.14?
The last discussions here point towards making this a breaking update for meteor versions that do not provide async versions of the basic DB ops. I set the version in the `package.js` to 2.14 simply since this is the version I can do proper end-to-end tests with. I really depend on [this bug here](https://github.com/meteor/meteor/issues/12902) to get fixed, so that I can test this package in my own (quite large) meteor app.

2024-01-20 07:35 UTC, dallman2 commented
> Interesting, thought this would still enable the package for version 3.0-beta;
The package resolution system is not quite smart enough to make 2.x and 3.0 work together. My fix for now is just to comment it out for meteor 3 support and wait. I am not sure if this causes undefined behavior in the package though.
> Question here is: Was any of the check faulty, in the sense that: Was your configuration for Meteor-Files in the constructor correctly provided according to the docs but an error was thrown anyway? Otherwise I'd consider this normal behavior, since starting from node v15 unhandled promise rejections terminate the app, so you'd have to take care of managing this in your app.
From my investigations, some breaking change has taken place with `match` along the way, or one of the arguments being passed to it has had a breaking change. I don't think (but I could be wrong) that anything illegal is happening from the Meteor Files packages perspective. I need to investigate this more thoroughly, but for now I am just trying to get my app running on 3.0 to work out other major compatibility issues.
> The last discussions here point towards making this a breaking update for meteor versions that do not provide async versions of the basic DB ops. I set the version in the `package.js` to 2.14 simply since this is the version I can do proper end-to-end tests with. I really depend on [this bug here](https://github.com/meteor/meteor/issues/12902) to get fixed, so that I can test this package in my own (quite large) meteor app.
For fixing this issue, my solution was to delete everything from my `versions` file, and then comment out every single dependancy in my `packages` file. Then, I would uncomment them one by one and figure out which ones were causing issues. Also, be aware that specifying versions for many packages can cause issues right now for working with Meteor 3, and that some packages require you to specify their Meteor 3 beta version of the package in your `packages` file. This was a real drag, but by following the process I was able to isolate which packages were actually broken and needed to be cloned and patched.

2024-01-20 08:41 UTC, dr-dimitru commented
@bratelefant @dallman2 upon `meteor publish` of recent betas I was forced to set `api.versionsFrom('2.8.1')`.

Regarding `Match` and `check` it's known that build-in debuggers into VSCode and similar IDEs suppressing detailed output of `check` errors, disabling it or running in pure node.js environment error will explain missing or deprecated properties. Hope that helps

2024-01-20 08:49 UTC, dr-dimitru commented
@bratelefant @harryadel @dallman2 @jankapunkt [`3.0.0-beta.3` is out!](https://packosphere.com/ostrio/files/3.0.0-beta.3)

2024-01-20 09:09 UTC, dallman2 commented
@bratelefant @dr-dimitru Interesting about the `api.versionsFrom` call. For `3.0.0-beta.3`, what api versions did you use? I am not exactly sure how to find/ browse the code for that beta. On Monday, I will investigate the `check` calls more. From what I recall, there was one particular check that was failing consistently. The failure stemmed from calling the `FilesCollection` constructor without any arguments (again, I need to check up on the code again and reproduce).

2024-01-22 13:41 UTC, harryadel commented
I'm currently in the process of migrating our application to the latest beta. And I've an interesting finding to share:

Due to the removal of synchronous db calls, this had a weird implication where we had to rework the way files are found on the client side and linking 
```js
const photo = Photos.findOne(this._id)
return photo.link('original', Meteor.absoluteUrl())
```

```js
const photo = Photos.collection.findOne(image.metadata.thumb)
return Photos.link(photo, 'original', Meteor.absoluteUrl()) 
```
which is kinda of an awkward looking code. I'll keep you guys posted during the whole process.

2024-01-23 08:13 UTC, bratelefant commented
> I'm currently in the process of migrating our application to the latest beta. And I've an interesting finding to share:
> 
> Due to the removal of synchronous db calls, this had a weird implication where we had to rework the way files are found on the client side and linking
> 
> ```js
> const photo = Photos.findOne(this._id)
> return photo.link('original', Meteor.absoluteUrl())
> ```
> 
>  ```js
> const photo = Photos.collection.findOne(image.metadata.thumb)
> return Photos.link(photo, 'original', Meteor.absoluteUrl()) 
> ```
> 
> which is kinda of an awkward looking code. I'll keep you guys posted during the whole process.

I'm doing it like so on the server-side `await VAssets.findOneAsync(fileRef._id)).link()`, should work similar on the client side. The signature of your second call of `link` looks like the one from `core.js`.

I did focus solely on the server side in this PR, so the `client.js` is not using any async db methods yet.

2024-01-23 11:33 UTC, harryadel commented
Ok, so the tests are passing in our application. :tada: If you intend on releasing new changes, please let me know so we can iterate and quickly work things out. Otherwise great work! @bratelefant :clap:

2024-02-03 11:20 UTC, harryadel commented
We're currently in the latest stages of migrating our application packages before attempting to upgrade our application to 3.0 so if you're done @bratelefant  will @dr-dimitru release a new version?

2024-02-04 01:20 UTC, dallman2 commented
> We're currently in the latest stages of migrating our application packages before attempting to upgrade our application to 3.0 so if you're done @bratelefant  will @dr-dimitru release a new version?

Looking forward to a release as well. How specifically are you updating your project? Are you attempting to update all of your packages to 3.0 compatible versions before changing your meteor release to 3.0?

2024-02-04 16:56 UTC, dr-dimitru commented
@bratelefant thank you for the work done so far, I assume there no more changes planned?

@harryadel @dallman2 thank you for involvement and ability to test pre-release of this package, if everything runs and works at your end — I'm going to release next major version as soon as @bratelefant confirms there are no additional changes pending

Question to all of you — how are we going to explain changes and usage examples in the docs? Docs was large and important part of this package

2024-02-05 05:18 UTC, bratelefant commented
@dr-dimitru For my part all changes requested are finished now. If no other changes are requested, we should be fine.
Docs are a significant point, especially because this is a breaking update.

2024-02-05 05:32 UTC, dallman2 commented
In general, I think that we should be linking people to the larger Meteor 3 migration issues on GitHub as a primer. From there, we can link them to some of the migration tools (async codegen stuff). Once people have that basis of information, I think they will be ready to understand the implications of the breaking changes here. 

In short, we should update the docs with the assumption that people will be well versed in the broader meteor migration.

2024-02-05 08:26 UTC, harryadel commented
>Looking forward to a release as well. How specifically are you updating your project? Are you attempting to update all of your packages to 3.0 compatible versions before changing your meteor release to 3.0?

Exactly, we're running the latest versions of aldeed:collection2, aldeed:schema-index, dburles:mongo-collection-instances and many other packages so when we make the leap it'll be a lot easier.

>Question to all of you — how are we going to explain changes and usage examples in the docs? Docs was large and important part of this package

Maybe like @dallman2 suggested, a little comment pointing to the [migration docs](https://guide.meteor.com/prepare-meteor-3.0#:~:text=In%20the%20new%20Meteor%203.0,moving%20to%20async%20and%20await%20.) and how it impacts our package.

2024-02-05 09:54 UTC, dallman2 commented
> Maybe like @dallman2 suggested, a little comment pointing to the [migration docs](https://guide.meteor.com/prepare-meteor-3.0#:~:text=In%20the%20new%20Meteor%203.0,moving%20to%20async%20and%20await%20.) and how it impacts our package.

We used [this](https://github.com/minhna/meteor-async-migration) to do the bulk of our migration to async. It has some burrs around the edges, but it saved time overall. Very easy link to miss in the docs. Another doc to check out is [this Google Doc](https://docs.google.com/document/d/1XxHE5MQaS0-85HQ-bkiXxmGlYi41ggkX3F-9Rjb9HhE/edit#heading=h.65xi3waq9bb). Its a little all over the place, but worth the read to learn about some very important nuances with the migration.

2024-02-05 10:41 UTC, bratelefant commented
I get some errors while regularly doing `meteor update --release 3.0-beta.0`, namely

```
While selecting package versions:
error: Conflict: Constraint webapp@1.3.10 is not satisfied by webapp 2.0.0-beta300.0.

...
webapp@1.3.10 <- ostrio:cookies 2.7.2 <- ostrio:files 2.3.3
´´´

Do we also need changes in `ostrio:cookies`, or how did you guys work around this for testing on meteor 3.0 beta?

2024-02-05 10:47 UTC, harryadel commented
@bratelefant I use the exclamation mark in packages to get over such restrictions

```
ostrio:files@3.0.0-beta.3!
```

2024-02-05 10:51 UTC, dallman2 commented
> Do we also need changes in `ostrio:cookies`, or how did you guys work around this for testing on meteor 3.0 beta?

In general, my solution was to packages that were causing issues and modify their `package.js` manually. Most packages were compatible with Meteor 3.0, but had an API constraint of 2.x. In this case, I would check if the `cookies` package has a 3.0 compatible version and explicitly require it in this package.

2024-02-06 10:26 UTC, harryadel commented
Now, as I'm attempting to upgrade our application to 3.0, I get these errors

```
                                                                                                                                      
   While selecting package versions:                                                                                                  
   error: Conflict: Constraint webapp@1.13.2 is not satisfied by webapp 2.0.0-beta300.0.                                              
   Constraints on package "webapp":                                                                                                   
   * webapp@~2.0.0-beta300.0 <- top level                                                                                             
   * webapp@2.0.0-beta300.0 <- meteor-base 1.5.2-beta300.0                                                                            
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base      
   3.0.0-beta300.0 <- accounts-password 3.0.0-beta300.0                                                                               
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password  
   3.0.0-beta300.0                                                                                                                    
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- webapp 2.0.0-beta300.0 <- autoupdate 2.0.0-beta300.0                    
   * webapp@2.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base 3.0.0-beta300.0 <-                  
   accounts-password 3.0.0-beta300.0                                                                                                  
   * webapp@2.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password 3.0.0-beta300.0                 
   * webapp@2.0.0-beta300.0 <- autoupdate 2.0.0-beta300.0                                                                             
   * webapp@2.0.0-beta300.0 <- mongo 2.0.0-beta300.0                                                                                  
   * webapp@1.13.2 <- ostrio:files 3.0.0-beta.3                                                                                       
   * webapp@1.3.10 <- ostrio:cookies 2.7.2 <- ostrio:files 3.0.0-beta.3                                                               


   Conflict: Constraint mongo@1.16.1 is not satisfied by mongo 2.0.0-beta300.0.                                                       
   Constraints on package "mongo":                                                                                                    
   * mongo@2.0.0-beta300.0 <- top level                                                                                               
   * mongo@~2.0.0-beta300.0 <- top level                                                                                              
   * mongo@2.0.0-beta300.0 <- reactive-dict 1.3.2-beta300.0                                                                           
   * mongo@2.0.0-beta300.0 <- accounts-base 3.0.0-beta300.0 <- accounts-password 3.0.0-beta300.0                                      
   * mongo@1.16.1 <- ostrio:files 3.0.0-beta.3                                                                                        
   * mongo@1.10.1 || 1.12.0 || 2.0.0-beta300.0 <- aldeed:collection2 4.0.0                                                            
   * mongo@1.0.8 || 2.0.0-beta300.0 <- trusted-care:nested-collection-helpers-enhanced 0.0.3                                          
   * mongo@1.16.8 || 2.0.0-beta300.0 <- dburles:mongo-collection-instances 1.0.0-beta300.1                                            
   * mongo@1.16.8 || 2.0.0-beta300.0 <- lai:collection-extensions 1.0.0-beta300.1 <- dburles:mongo-collection-instances               
   1.0.0-beta300.1                                                                                                                    
                                                                                                                                      
   Conflict: Constraint ddp-client@2.6.1 is not satisfied by ddp-client 3.0.0-beta300.0.                                              
   Constraints on package "ddp-client":
   * ddp-client@~3.0.0-beta300.0 <- top level
   * ddp-client@3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base 3.0.0-beta300.0 <- accounts-password 3.0.0-beta300.0
   * ddp-client@3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password 3.0.0-beta300.0
   * ddp-client@3.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base 3.0.0-beta300.0 <-
   accounts-password 3.0.0-beta300.0
   * ddp-client@3.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password 3.0.0-beta300.0
   * ddp-client@2.6.1 <- ostrio:files 3.0.0-beta.3



  Conflict: Constraint webapp@1.3.10 is not satisfied by webapp 2.0.0-beta300.0.
   Constraints on package "webapp":
   * webapp@~2.0.0-beta300.0 <- top level
   * webapp@2.0.0-beta300.0 <- meteor-base 1.5.2-beta300.0
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base
   3.0.0-beta300.0 <- accounts-password 3.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password
   3.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- routepolicy 1.1.2-beta300.0 <- webapp 2.0.0-beta300.0 <- autoupdate 2.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-base 3.0.0-beta300.0 <-
   accounts-password 3.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- ddp-server 3.0.0-beta300.0 <- ddp 1.4.2-beta300.0 <- accounts-password 3.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- autoupdate 2.0.0-beta300.0
   * webapp@2.0.0-beta300.0 <- mongo 2.0.0-beta300.0
   * webapp@1.13.2 <- ostrio:files 3.0.0-beta.3
   * webapp@1.3.10 <- ostrio:cookies 2.7.2 <- ostrio:files 3.0.0-beta.3
   
=> Your application has errors. Waiting for file change.

```

Does this pertain to the problem raised by @jankapunkt ?

https://forums.meteor.com/t/solved-how-to-publish-packages-with-specific-meteor-3-0-version-to-resolve-top-level-conflicts/61091/3

2024-02-06 10:40 UTC, dallman2 commented
@harryadel you have several packages that are relying on old packages, even though they have a new 'beta' version. For me, the easiest solution was to clone the packages that relied on old versions and manually update their dependencies. Eventually, most packages will update and everything will be easy again. Until then, manual updates were the easiest way I found to actually be able to test meteor 3.

2024-02-06 11:06 UTC, dallman2 commented
Ahhh I see. My mistake, I was having flashbacks to my migration a few months ago.

From the looks of the files changed in the pull request, version 2.14 is still a valid API level to use, along with the 3.0 beta API level. Explicitly stating that the package should use the new versions of the packages you're having issues with, or just removing the 2.14 API level altogether could both be solutions.

2024-02-06 12:24 UTC, harryadel commented
>Ahhh I see. My mistake, I was having flashbacks to my migration a few months ago.


![meteor-horror](https://github.com/veliovgroup/Meteor-Files/assets/6644545/40916d8d-0968-466f-b221-209ae05d1a70)

More like a PTSD :sweat_smile:

2024-02-06 19:45 UTC, dallman2 commented
Got a chance to look into this more today, maybe try clearing the contents of the `.versions` file and re-running the project. I have had issues in the past where a dependancy resolution gets messed up because of a lingering out of date version in that file.

2024-02-09 23:17 UTC, dr-dimitru commented
@bratelefant @harryadel @dallman2 @jankapunkt [`ostrio:files@3.0.0-beta.4`](https://packosphere.com/ostrio/files/3.0.0-beta.4) is out!

Now with `api.versionsFrom(['2.14', '3.0-beta.0'])` and `ostrio:cookies@2.8.0` so you shouldn't experience dependency issues, let me know!

2024-02-09 23:40 UTC, dallman2 commented
@dr-dimitru `beta.4` successfully build in my project! Also compatible with the path we discussed in the `cookies` repo

2024-02-10 10:39 UTC, harryadel commented
@dr-dimitru Thank you will give it a try and report back :+1:

2024-02-26 09:24 UTC, harryadel commented
Aside from the issue listed [here](https://github.com/veliovgroup/meteor-cookies/issues/21#issuecomment-1952156765), the packages are working wonderfully for us. Thank you @bratelefant, amazing work :clap: :clap: :clap:

2024-03-24 14:28 UTC, harryadel commented
When I tried to update the cookies package it led to a conflict since ostrio:files is reliant on 2.8

![Screenshot_2024-03-24_16-26-47](https://github.com/veliovgroup/Meteor-Files/assets/6644545/d47dc41e-e788-4455-a860-ffa8ca9735aa)

@dr-dimitru

2024-03-24 19:11 UTC, dallman2 commented
> EDIT: Do any of you guys use Cordova? I run into a couple of issues when async changes paired with Cordova.

We don't, unsure of others in the thread. What issues are you having?

2024-03-25 08:03 UTC, harryadel approved these changes

2024-03-25 08:03 UTC, harryadel commented on server.js
>  const bound = Meteor.bindEnvironment(callback => callback());
Just out of sheer curiosity, is there still a need for `Meteor.bindEnvironment`? Meteor 3.0 no longer uses fibers/futures.

2024-03-25 19:45 UTC, dr-dimitru commented on server.js
>  const bound = Meteor.bindEnvironment(callback => callback());
@harryadel good catch, it should be safe to remove it now.
@bratelefant wdyt?

2024-03-25 19:48 UTC, dr-dimitru commented
@harryadel please give it freshly published [`v3.0.0-beta.5`](https://packosphere.com/ostrio/files/3.0.0-beta.5) a try. Issue from your screenshot should be solved now. LMK

2024-03-26 05:37 UTC, harryadel commented
@dallman2 Still trying to pint point the root cause, though I figured to share my problems in case someone else ran into them.

2024-03-26 05:39 UTC, dallman2 commented
Will try this update tomorrow and let you know how it goes (I'm on Pacific coast time :P). I've been deep into css modules all day so I'm going to have to shift a bit to deal with the files collection.

2024-04-29 07:14 UTC, harryadel commented
@bratelefant @dr-dimitru Maybe it's time to release a new beta that relies on the latest RC instead of beta?

2024-04-29 09:15 UTC, jankapunkt commented
A  beta release would be awesome so I can do some integration tests with our projects and give you early feedback

2024-04-29 10:19 UTC, dr-dimitru commented
@harryadel @bratelefant @jankapunkt [`3.0.0-beta.6` is out](https://packosphere.com/ostrio/files/3.0.0-beta.6) with support for `meteor@3.0.0-rc.0`

2024-05-21 14:55 UTC, harryadel commented
@bratelefant Can you make `onBeforeUpload` on the client side async please? 
https://github.com/bratelefant/Meteor-Files/blob/69cddf91c6432ac872d70218949d9537a143d667/upload.js#L688

`onBeforeUpload` is an isomorphic method that runs on both server and client so sync operations would only work on client side and fail on serverside on 3.0 but async operation works on both. So, I suggest to make all isomorphic methods async.

cc @bratelefant @dr-dimitru

2024-05-23 14:13 UTC, make-github-pseudonymous-again commented
> Can you make `onBeforeUpload` on the client side async please? https://github.com/bratelefant/Meteor-Files/blob/69cddf91c6432ac872d70218949d9537a143d667/upload.js#L688
> 
> `onBeforeUpload` is an isomorphic method that runs on both server and client so sync operations would only work on client side and fail on serverside on 3.0 but async operation works on both. So, I suggest to make all the callers of isomorphic methods support async functions.
> 
> cc @bratelefant @dr-dimitru

I think in general all hooks should be async. Any of them might require interacting with the database which is now something that is async by default.

2024-05-23 16:14 UTC, make-github-pseudonymous-again commented
@bratelefant My only pain point so far with the current state of the PR is the lack of documentation: took me some time to figure out that the callback version of `Meteor.write` was gone. The error you get by trying to use the old signature on the new one is just a timeout, if you are lucky to have configured one (tests). This PR could have been done without this change, right? If we are aiming at a new version of `ostrio:files` without any callback-style functions, then we should also change the client signatures (`insert`, etc.).

2024-05-23 16:32 UTC, bratelefant commented
> Can you make `onBeforeUpload` on the client side async please? https://github.com/bratelefant/Meteor-Files/blob/69cddf91c6432ac872d70218949d9537a143d667/upload.js#L688

That'd be definitely one major point to add to this pr. Did all changes with focus on the server side, client only methods did not get touched.

> `onBeforeUpload` is an isomorphic method that runs on both server and client so sync operations would only work on client side and fail on serverside on 3.0 but async operation works on both. So, I suggest to make all the callers of isomorphic methods support async functions.

Yes, in our discussion here at some point we decided to make this an update with breaking changes by removing all sync methods on the server side.

@make-github-pseudonymous-again I tried to keep documention in the server side method comments aligned with the code changes, but that was definitely not checked agains tests / code.

I would be really grateful if someone could jump on the bandwagon and contribute to the PR,  I am having a pretty 'crunchy' time at work atm

2024-05-24 07:47 UTC, make-github-pseudonymous-again commented on server.js
> +        if (_id) result._id = _id;
`onUploaded` is event worse: the `fileRef` is simply `undefined`.

2024-06-28 11:14 UTC, dr-dimitru commented on server.js
> +        if (_id) result._id = _id;
@bratelefant do you think we should address this as part of this PR?

2024-08-27 22:29 UTC, 67726e commented on server.js
> +        if (_id) result._id = _id;
I'm getting similar `undefined` results after an upload via

```
ContactFileCollection.insert({
  file: file,
}).on('uploaded', (uploadError, file) => {
  console.log('===== uploaded', uploadError, file)
```

2024-09-25 15:22 UTC, StorytellerCZ commented
Any update on this?

2024-09-26 09:35 UTC, harryadel commented
Hello, I created a PR to allow us to use async onBeforeUpload https://github.com/bratelefant/Meteor-Files/pull/2

2024-10-08 21:45 UTC, hluz commented
Hi everyone... Not trying to be pushy, but this is one of the few remaining hurdles in migrating to Meteor 3 for many of us. Even if it was only a new beta version adding the async onBeforeUpload changes would help... @dr-dimitru @StorytellerCZ @jankapunkt

2024-11-14 10:56 UTC, wolasss commented
Hey, any updates on this ?

2025-01-04 08:59 UTC, jankapunkt commented
Hey @all I can take a look at this finally... may need some time though to test everything with our existing staging projects

2025-01-04 16:53 UTC, jankapunkt requested changes
First of all big thanks for this PR and the all the work on this. I am currently creating a repro to test all this with a GridFS setup but it looks good for minimal functionality.

However, I found a few thinks which I commented each in the respective lines.

@dr-dimitru I think there is still the big question if there is the intent to support Meteor 2 and 3 or doing a clean break and just go for Meteor 3 and onwards.

Besides that I found there are much more things to be done **after merging this pR**:

- docs need to be updated
- server.js should be refactored into smaller files to reduce mental load during debugging sessions

@dr-dimitru if you have time we could get in contact this week and shortly talk about how we can move forward with this one. I'm willing to finish the great work that has been done here but I first think we need a clear mission for a stable 3.x release

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +    WebApp.connectHandlers.use(async (httpReq, httpResp, next) => {
In Meteor 3 connectHandlers is only there for backwards compat but I don't know for how long. Since connect is replaced with express this is now `WebApp.handlers`

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +    if (partiral || (http.params?.query?.play && (http.params.query.play === 'true'))) {
I think `partiral` is meant to be `partial`?

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +          if ((await cursor.countAsync()) > 0) {
cursor.count should not be used anymore in favor of `async collection.countDocuments(query)` or `async collection.estimateDocumentsCount`

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +            self.removeAsync(selector);
missing await

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +        if (_id) result._id = _id;
I would adress it in a separete PR if it will not interfere with this one (merge conflicts etc.) otherwise directly here

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +      opts = {};
if `opts = {};` then it might be safe to use `proceedAfterUpload = { ...opts };` ?

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +    let mustCreateFileFirst = false;
It would be great to have a few comments that summarize what happens here.
If I get it right this ensures directory and file exists for writing the data, correct?

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +    let mustCreateFileFirst = false;
this seems to be redundant with the code in line 1278++ and could be extracted into a method

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +          controller.abort();
Note, that Node 14 has no native `AbortController`  implementation and a polyfill is needed; so this might cause issues when we want to have backwards compat with 2.x

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +      if (!result.size) {
if this is newly added behavior then please add a few comments. also - is `pipeline` available in node 14?

2025-01-04 16:53 UTC, jankapunkt commented on server.js
> +        this.onAfterUpload && this.onAfterUpload.call(this, fileRef);
missing await

2025-01-04 16:53 UTC, jankapunkt commented on server.js
>          this.unlink(file);
this is debatable but if you want to use sequential for each async then you have to return the promise, generated by `this.unlink` in order to have the underlying `await` to take effect.

otherwise I don't know if this has any implications, like race condition etc.

2025-01-05 16:55 UTC, dr-dimitru commented
@jankapunkt thank you for your review, I'll go though it, and see how much I can fix, then we decide if call is needed, looking forward to new beta release

2025-01-16 07:39 UTC, jankapunkt commented
@dr-dimitru if you want you can merge this into `migration/3.0` branch and I can continue to work on the things I commented

2025-01-18 19:59 UTC, dr-dimitru commented
@jankapunkt wasn't able to merge to `migration/3.0` due to source branch ownership and this error:
```
There are no new commits between base branch 'migration/3.0' and head branch 'master'
```

Created branch called — `migration-branch/3.0` feel free to PR your latest changes from `migration/3.0`

2025-01-18 20:01 UTC, merged

2025-01-18 20:05 UTC, dr-dimitru commented
@bratelefant thank you for the great start on these changes
@harryadel @hluz @make-github-pseudonymous-again @StorytellerCZ thank you for all additional input and changes

@jankapunkt looking forward to finish this up. I got local setup ready for tests and further fixes related to 3.0; And I should have time for this in coming weeks

2025-01-19 09:21 UTC, dr-dimitru commented
work done in this PR resumed in #895